# Generated by Django 6.0.7 on 2026-07-12 13:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('language', models.CharField(choices=[('bn', 'Bangla'), ('en', 'English'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('category', models.CharField(choices=[('medical', 'Medical'), ('fire', 'Fire'), ('accident', 'Accident'), ('crime', 'Crime'), ('flood', 'Flood'), ('utility', 'Utility'), ('public_service', 'Public Service'), ('infrastructure', 'Infrastructure'), ('other', 'Other')], max_length=50)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('summary', models.TextField()),
                ('suggested_action', models.TextField()),
                ('confidence', models.FloatField()),
                ('possible_duplicate', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('assigned', 'Assigned'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.report')),
            ],
        ),
    ]
