# Generated by Django 6.0.7 on 2026-07-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reportactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='duplicate_similarity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
