# Generated by Django 6.0.7 on 2026-07-12 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_duplicate_similarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_reports', to='reports.report'),
        ),
    ]
